#################### OPENAI API SERVER ####################
# openai api server alternative
FROM vllm/vllm-openai:latest AS vllm-openai

RUN pip install --no-cache-dir git+https://github.com/huggingface/transformers@21fac7abba2a37fae86106f87fcf9974fd1e3830  \
&& pip3 install --no-cache-dir accelerate \
&& pip3 install --no-cache-dir qwen-vl-utils

# install additional dependencies for openai api server
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install accelerate hf_transfer 'modelscope!=1.15.0'

ENV VLLM_USAGE_SOURCE production-docker-image


ENTRYPOINT ["python3", "-m", "vllm.entrypoints.openai.api_server"]
#################### OPENAI API SERVER ####################